import "./globals.css";
import {Roboto} from "next/font/google";
import {Header} from "@/app/components/Header";

const roboto = Roboto({
    subsets: ["latin"],
    weight: ["400","700"],
    variable: "--font-roboto",
    display: 'swap'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
